### ISSUE TITLE
Installation of 1.1.0 causes 'gem help commands' to fail

### ISSUE THREAD

**Issue by ged** [seattlerb/rubygems-sandbox#3]
With Rubygems 1.8.10, installing rubygems-sandbox causes the Rubygems 'help commands' command to fail:

```
$ gem -v
1.8.10

$ gem help commands
GEM commands are:
[snip...]

$ gem install rubygems-sandbox
Fetching: rubygems-sandbox-1.1.0.gem (100%)
Successfully installed rubygems-sandbox-1.1.0
1 gem installed
Installing RDoc documentation for rubygems-sandbox-1.1.0...

$ gem help commands
ERROR:  While executing gem ... (ArgumentError)
    wrong number of arguments (0 for 1)
[...]/rubygems/command.rb:116:in `initialize'
[...]/rubygems/command_manager.rb:177:in `new'
[...]/rubygems/command_manager.rb:177:in `load_and_instantiate'
[...]/rubygems/command_manager.rb:103:in `[]'
[...]/rubygems/commands/help_command.rb:116:in `block in execute'
[...]/rubygems/commands/help_command.rb:115:in `each'
[...]/rubygems/commands/help_command.rb:115:in `execute'
[...]/rubygems/command.rb:278:in `invoke'
[...]/rubygems/command_manager.rb:147:in `process_args'
[...]/rubygems/command_manager.rb:117:in `run'
[...]/rubygems/gem_runner.rb:65:in `run'
~/.rvm/rubies/ruby-1.9.2-p290/bin/gem:21:in `<main>'

$ gem uninstall rubygems-sandbox
Successfully uninstalled rubygems-sandbox-1.1.0

$ gem help commands
GEM commands are:
[snip...]
```

This happens under at least Ruby 1.8.7-p249 running from /usr and 1.9.2-p290 running via RVM.

**Comment by zenspider** [comment]
I think this was fixed long ago. Sorry I missed this.
